importar tortuga

ventana  =  tortuga . Pantalla ()
ventana _ bgcolor ( "#8DF2E8" )
ventana _ title ( "Mi nombre con Python Turtle" )
lápiz  =  tortuga . tortuga ()

lápiz _ arriba ()
lápiz _ atrás ( 700 )
lápiz _ abajo ()

lápiz _ color ( "#260101" )
lápiz _ color de relleno ( "#41BFB3" )

""" J """
lápiz _ comenzar_llenar ()
lápiz _ izquierda ( 70 )
lápiz _ adelante ( 200 )
lápiz _ derecha ( 135 )
lápiz _ adelante ( 200 )
lápiz _ izquierda ( 135 )
lápiz _ adelante ( 200 )
lápiz _ derecha ( 135 )
lápiz _ adelante ( 200 )
lápiz _ correcto ( 90 )
lápiz _ adelante ( 20 )
lápiz _ correcto ( 90 )
lápiz _ adelante ( 160 )
lápiz _ izquierda ( 135 )
lápiz _ adelante ( 200 )
lápiz _ derecha ( 135 )
lápiz _ adelante ( 200 )
lápiz _ izquierda ( 135 )
lápiz _ adelante ( 160 )
lápiz _ correcto ( 90 )
lápiz _ adelante ( 20 )
lápiz _ end_fill ()

lápiz _ arriba ()
lápiz _ derecha ( 160 )
lápiz _ adelante ( 350 )
lápiz _ abajo ()

""" U """
lápiz _ comenzar_llenar ()
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 200 )
lápiz _ correcto ( 90 )
lápiz _ adelante ( 20 )
lápiz _ correcto ( 90 )
lápiz _ adelante ( 200 )
lápiz _ correcto ( 90 )
lápiz _ adelante ( 20 )
lápiz _ end_fill ()

lápiz _ arriba ()
lápiz _ izquierda ( 180 )
lápiz _ adelante ( 60 )
lápiz _ abajo ()

""" L """
lápiz _ comenzar_llenar ()
lápiz _ adelante ( 220 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 100 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 180 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 20 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 160 )
lápiz _ correcto ( 90 )
lápiz _ adelante ( 60 )
lápiz _ correcto ( 90 )
lápiz _ adelante ( 180 )
lápiz _ correcto ( 90 )
lápiz _ adelante ( 160 )
lápiz _ correcto ( 90 )
lápiz _ adelante ( 200 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 20 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 220 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 200 )
lápiz _ end_fill ()

lápiz _ arriba ()
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 250 )
lápiz _ abajo ()

""" I """
lápiz _ comenzar_llenar ()
lápiz _ adelante ( 200 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 200 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 20 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 180 )
lápiz _ correcto ( 90 )
lápiz _ adelante ( 160 )
lápiz _ correcto ( 90 )
lápiz _ adelante ( 180 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 20 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 200 )
lápiz _ end_fill ()

lápiz _ arriba ()
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 250 )
lápiz _ abajo ()

""" YO """
lápiz _ comenzar_llenar ()
lápiz _ adelante ( 200 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 20 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 180 )
lápiz _ correcto ( 90 )
lápiz _ adelante ( 70 )
lápiz _ correcto ( 90 )
lápiz _ adelante ( 180 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 20 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 180 )
lápiz _ correcto ( 90 )
lápiz _ adelante ( 70 )
lápiz _ correcto ( 90 )
lápiz _ adelante ( 180 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 20 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 200 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 200 )
lápiz _ end_fill ()

lápiz _ arriba ()
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 250 )
lápiz _ abajo ()

""" N """
lápiz _ comenzar_llenar ()
lápiz _ adelante ( 200 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 20 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 180 )
lápiz _ correcto ( 90 )
lápiz _ adelante ( 180 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 20 )
lápiz _ izquierda ( 90 )
lápiz _ adelante ( 200 )
lápiz _ end_fill ()

tortuga _ hecho ()